import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Fixture from './models/Fixture.js';
import { getPredictedFixturesGroupedByLeague, clearPredictionCache } from './services/fixtureCardService.js';

dotenv.config();

async function checkDate(dateStr) {
    clearPredictionCache();
    // Use the actual service
    const result = await getPredictedFixturesGroupedByLeague(dateStr);
    let count = 0;
    for (const group of result) {
        count += group.matches.length;
    }
    console.log(`${dateStr}: ${count} predictions`);
}

async function test() {
    await mongoose.connect(process.env.MONGO_URI);
    
    // We already cleared and recalculated everything with recalculate_predictions.js
    // Let's just check the counts generated by the service
    await checkDate("2026-08-10");
    await checkDate("2026-08-12");
    await checkDate("2026-08-13");
    await checkDate("2026-08-14");
    
    mongoose.connection.close();
}

test();
